[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/api/paddle/webhook"
  to = "/.netlify/functions/paddle-webhook"
  status = 200

[[headers]]
  for = "/update/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"
